<?php
/**
 * Created by PhpStorm.
 * User: guild
 * Date: 8/19/2018
 * Time: 11:31 PM
 */

class Cliente extends Pessoa{
    private $email;
    private $endereco;

    public function __construct($nome = null, $cpf = null, $id = null, $email = null, $endereco = null){
        parent::__construct($nome, $cpf, $id);
        $this->email = $email;
        $this->endereco = $endereco;

    }

    public function getNome()
    {
        return parent::getNome(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    public function toArray()
    {
        $r = parent::toArray(); // TODO: Change the autogenerated stub
        $r["email"] = $this->getEmail();
        $r["endereco"] = $this->getEndereco();
        $r["idCliente"] = parent::getId();
        return $r;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getEndereco()
    {
        return $this->endereco;
    }

    /**
     * @param mixed $endereco
     */
    public function setEndereco($endereco)
    {
        $this->endereco = $endereco;
    }

    public function setNome($nome)
    {
        parent::setNome($nome); // TODO: Change the autogenerated stub
    }

    public function getCpf()
    {
        return parent::getCpf(); // TODO: Change the autogenerated stub
    }

    public function setCpf($cpf)
    {
        parent::setCpf($cpf); // TODO: Change the autogenerated stub
    }

    public function getId()
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }

    public function setId($id)
    {
        parent::setId($id); // TODO: Change the autogenerated stub
    }

    public function __toString()
    {
        return parent::__toString() . "Email: {$this->email} <br> Endereço: {$this->endereco} <br>"; // TODO: Change the autogenerated stub
    }


}
?>