<?php
/**
 * Created by PhpStorm.
 * User: guild
 * Date: 8/20/2018
 * Time: 12:42 AM
 */

class Conjuge extends Pessoa{
    private $cliente;

    public function __construct($nome = null, $cpf = null, $id = null, $cliente = null){
        parent::__construct($nome, $cpf, $id);
        $this->cliente = $cliente;

    }

    /**
     * @return mixed
     */
    public function getCliente()
    {
        return $this->cliente;
    }

    /**
     * @param mixed $cliente
     */
    public function setCliente($cliente)
    {
        $this->cliente = $cliente;
    }

    public function getNome()
    {
        return parent::getNome(); // TODO: Change the autogenerated stub
    }

    public function toArray()
    {
        $r = parent::toArray(); // TODO: Change the autogenerated stub
        $r["idConjuge"] = parent::getId();
        $r["fk_idCliente"] = $this->cliente->getId();
        return $r;
    }

    public function setNome($nome)
    {
        parent::setNome($nome); // TODO: Change the autogenerated stub
    }

    public function getCpf()
    {
        return parent::getCpf(); // TODO: Change the autogenerated stub
    }

    public function setCpf($cpf)
    {
        parent::setCpf($cpf); // TODO: Change the autogenerated stub
    }

    public function getId()
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }

    public function setId($id)
    {
        parent::setId($id); // TODO: Change the autogenerated stub
    }

    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }


}
?>